#ifndef header_h
#define header_h

String file1=
"<!DOCTYPE html>\r\n"
"<html>\r\n"
"<head>\r\n"
"<style>\r\n"
"body {\r\n"
"    height: 100vh;\r\n"
"    padding: 0;\r\n"
"    margin: 0;\r\n"
"    overflow: hidden;\r\n"
"	background-color: #2b3e4c;\r\n"
"}\r\n"
"a:link, a:visited {\r\n"
"	margin: auto;\r\n"
"    background-color: #f44336;\r\n"
"    color: white;\r\n"
"	font-size: 300%;\r\n"
"    padding: 8%;\r\n"
"	margin: 1em;\r\n"
"    text-align: center;\r\n"
"    text-decoration: none;\r\n"
"    display: inline-block;\r\n"
"	border-radius: 20px;\r\n"
"}\r\n"
"h1{\r\n"
"text-shadow: 1px 0.5px red;\r\n"
"font-family: \"Georgia\", Times, serif;\r\n"
"margin: 5%;\r\n"
"color: #fff;\r\n"
"}\r\n"
"a:hover, a:active {\r\n"
"    background-color: #F2A533;\r\n"
"}\r\n"
"</style>\r\n"
"</head>\r\n"
"<body>\r\n"
"<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n"
"<div class=\"danBkg display-none\"></div>\r\n"
"<center>\r\n"
"<h1>Choose an option to change:</h1>\r\n"
"<hr style=\"width: 80%; height: 80%; color: white;\">\r\n"
"<h1>\r\n"
"</h1>\r\n"
"<a href=\"/wifi\" target=\"_self\">WiFi</a>\r\n"
"<a href=\"/user\" target=\"_self\">Name</a>\r\n"
"</body>\r\n"
"</center>\r\n"
"</html>\r\n";

#endif