#ifndef header_h
#define header_h

String file1=
"<!DOCTYPE html>\r\n"
"<html>\r\n"
"<head>\r\n"
"<style>\r\n"
"h1{\r\n"
"text-shadow: 2px 1.5px red;\r\n"
"font-family: \"Georgia\", Times, serif;\r\n"
"margin: 5%;\r\n"
"}\r\n"
"body {\r\n"
"  font: normal 18px/1.5 \"Fira Sans\", \"Helvetica Neue\", sans-serif;\r\n"
"  background-color: #2b3e4c;\r\n"
"  color: #fff;\r\n"
"  padding: 50px 0;\r\n"
"}\r\n"
"\r\n"
".container {\r\n"
"  width: 80%;\r\n"
"  max-width: 1200px;\r\n"
"  margin: 0 auto;\r\n"
"}\r\n"
"\r\n"
".container * {\r\n"
"  box-sizing: border-box;\r\n"
"  border-radius: 20px;\r\n"
"}\r\n"
"\r\n"
".flex-outer,\r\n"
".flex-inner {\r\n"
"  list-style-type: none;\r\n"
"  padding: 0;\r\n"
"}\r\n"
"\r\n"
".flex-outer {\r\n"
"  max-width: 800px;\r\n"
"  margin: 0 auto;\r\n"
"}\r\n"
"\r\n"
".flex-outer li,\r\n"
".flex-inner {\r\n"
"  display: flex;\r\n"
"  flex-wrap: wrap;\r\n"
"  align-items: center;\r\n"
"}\r\n"
"\r\n"
".flex-inner {\r\n"
"  padding: 0 8px;\r\n"
"  justify-content: space-between;  \r\n"
"}\r\n"
"\r\n"
".flex-outer > li:not(:last-child) {\r\n"
"  margin-bottom: 20px;\r\n"
"}\r\n"
"\r\n"
".flex-outer li label,\r\n"
".flex-outer li p {\r\n"
"  padding: 8px;\r\n"
"  font-weight: 300;\r\n"
"  letter-spacing: .09em;\r\n"
"  text-transform: uppercase;\r\n"
"}\r\n"
"\r\n"
".flex-outer > li > label,\r\n"
".flex-outer li p {\r\n"
"  flex: 1 0 120px;\r\n"
"  max-width: 220px;\r\n"
"}\r\n"
"\r\n"
".flex-outer > li > label + *,\r\n"
".flex-inner {\r\n"
"  flex: 1 0 220px;\r\n"
"}\r\n"
"\r\n"
".flex-outer li p {\r\n"
"  margin: 0;\r\n"
"}\r\n"
"\r\n"
".flex-outer li input:not([type='checkbox']),\r\n"
".flex-outer li textarea {\r\n"
"  padding: 15px;\r\n"
"  border: none;\r\n"
"}\r\n"
"\r\n"
".flex-outer li button {\r\n"
"  margin-left: auto;\r\n"
"  padding: 8px 16px;\r\n"
"  border: none;\r\n"
"  background: red;\r\n"
"  color: #f2f2f2;\r\n"
"  text-transform: uppercase;\r\n"
"  letter-spacing: .09em;\r\n"
"  border-radius: 2px;\r\n"
"}\r\n"
"\r\n"
".flex-inner li {\r\n"
"  width: 100px;\r\n"
"}\r\n"
"@media screen and (max-width: 600px) {\r\n"
"    .col-25, .col-75, input[type=submit] {\r\n"
"        width: 100%;\r\n"
"        margin-top: 0;\r\n"
"    }\r\n"
"}\r\n"
"</style>\r\n"
"</head>\r\n"
"<body>\r\n"
"<center>\r\n"
"<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n"
"<h1>Name settings</h1>\r\n"
"</center>\r\n"
"<div class=\"container\">\r\n"
"  <form action=\"/name_commit\">\r\n"
"    <ul class=\"flex-outer\">\r\n"
"      <li>\r\n"
"        <label for=\"first-name\">Name:</label>\r\n"
"        <input type=\"text\" name=\"#\" value=\"\" id=\"first-name\" placeholder=\"Current: \">\r\n"
"      </li>\r\n"
"      <li>\r\n"
"        <button type=\"submit\">Submit</button>\r\n"
"      </li>\r\n"
"    </ul>\r\n"
"  </form>\r\n"
"  </div>\r\n"
"</body>\r\n"
"\r\n"
"</html>\r\n";

#endif