String index_html =
"<!DOCTYPE html>\r\n"
"<html>\r\n"
"<head>\r\n"
"<style>\r\n"
"body {\r\n"
"    height: 100vh;\r\n"
"    padding: 0;\r\n"
"    margin: 0;\r\n"
"    overflow: hidden;\r\n"
"  background-color: #2b3e4c;\r\n"
"}\r\n"
"a:link, a:visited {\r\n"
" margin: auto;\r\n"
"    background-color: #f44336;\r\n"
"    color: white;\r\n"
" font-size: 300%;\r\n"
"    padding: 8%;\r\n"
" margin: 1em;\r\n"
"    text-align: center;\r\n"
"    text-decoration: none;\r\n"
"    display: inline-block;\r\n"
" border-radius: 20px;\r\n"
"}\r\n"
"h1{\r\n"
"text-shadow: 1px 0.5px red;\r\n"
"font-family: \"Georgia\", Times, serif;\r\n"
"margin: 5%;\r\n"
"color: #fff;\r\n"
"}\r\n"
"a:hover, a:active {\r\n"
"    background-color: #F2A533;\r\n"
"}\r\n"
"</style>\r\n"
"</head>\r\n"
"<body>\r\n"
"<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n"
"<div class=\"danBkg display-none\"></div>\r\n"
"<center>\r\n"
"<h1>Choose an option to change:</h1>\r\n"
"<hr style=\"width: 80%; height: 80%; color: white;\">\r\n"
"<h1>\r\n"
"</h1>\r\n"
"<a href=\"/wifi\" target=\"_self\">WiFi</a>\r\n"
"<a href=\"/name\" target=\"_self\">Name</a>\r\n"
"</body>\r\n"
"</center>\r\n"
"</html>\r\n";




String name1_html=
"<!DOCTYPE html>\r\n"
"<html>\r\n"
"<head>\r\n"
"<style>\r\n"
"h1{\r\n"
"text-shadow: 2px 1.5px red;\r\n"
"font-family: \"Georgia\", Times, serif;\r\n"
"margin: 5%;\r\n"
"}\r\n"
"body {\r\n"
"  font: normal 18px/1.5 \"Fira Sans\", \"Helvetica Neue\", sans-serif;\r\n"
"  background-color: #2b3e4c;\r\n"
"  color: #fff;\r\n"
"  padding: 50px 0;\r\n"
"}\r\n"
"\r\n"
".container {\r\n"
"  width: 80%;\r\n"
"  max-width: 1200px;\r\n"
"  margin: 0 auto;\r\n"
"}\r\n"
"\r\n"
".container * {\r\n"
"  box-sizing: border-box;\r\n"
"  border-radius: 20px;\r\n"
"}\r\n"
"\r\n"
".flex-outer,\r\n"
".flex-inner {\r\n"
"  list-style-type: none;\r\n"
"  padding: 0;\r\n"
"}\r\n"
"\r\n"
".flex-outer {\r\n"
"  max-width: 800px;\r\n"
"  margin: 0 auto;\r\n"
"}\r\n"
"\r\n"
".flex-outer li,\r\n"
".flex-inner {\r\n"
"  display: flex;\r\n"
"  flex-wrap: wrap;\r\n"
"  align-items: center;\r\n"
"}\r\n"
"\r\n"
".flex-inner {\r\n"
"  padding: 0 8px;\r\n"
"  justify-content: space-between;  \r\n"
"}\r\n"
"\r\n"
".flex-outer > li:not(:last-child) {\r\n"
"  margin-bottom: 20px;\r\n"
"}\r\n"
"\r\n"
".flex-outer li label,\r\n"
".flex-outer li p {\r\n"
"  padding: 8px;\r\n"
"  font-weight: 300;\r\n"
"  letter-spacing: .09em;\r\n"
"  text-transform: uppercase;\r\n"
"}\r\n"
"\r\n"
".flex-outer > li > label,\r\n"
".flex-outer li p {\r\n"
"  flex: 1 0 120px;\r\n"
"  max-width: 220px;\r\n"
"}\r\n"
"\r\n"
".flex-outer > li > label + *,\r\n"
".flex-inner {\r\n"
"  flex: 1 0 220px;\r\n"
"}\r\n"
"\r\n"
".flex-outer li p {\r\n"
"  margin: 0;\r\n"
"}\r\n"
"\r\n"
".flex-outer li input:not([type='checkbox']),\r\n"
".flex-outer li textarea {\r\n"
"  padding: 15px;\r\n"
"  border: none;\r\n"
"}\r\n"
"\r\n"
".flex-outer li button {\r\n"
"  margin-left: auto;\r\n"
"  padding: 8px 16px;\r\n"
"  border: none;\r\n"
"  background: red;\r\n"
"  color: #f2f2f2;\r\n"
"  text-transform: uppercase;\r\n"
"  letter-spacing: .09em;\r\n"
"  border-radius: 2px;\r\n"
"}\r\n"
"\r\n"
".flex-inner li {\r\n"
"  width: 100px;\r\n"
"}\r\n"
"@media screen and (max-width: 600px) {\r\n"
"    .col-25, .col-75, input[type=submit] {\r\n"
"        width: 100%;\r\n"
"        margin-top: 0;\r\n"
"    }\r\n"
"}\r\n"
"</style>\r\n"
"</head>\r\n"
"<body>\r\n"
"<center>\r\n"
"<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n"
"<h1>Name settings</h1>\r\n"
"</center>\r\n"
"<div class=\"container\">\r\n"
"  <form action=\"/name_commit\">\r\n"
"    <ul class=\"flex-outer\">\r\n"
"      <li>\r\n"
"        <label for=\"first-name\">Name:</label>\r\n"
"        <input type=\"text\" name=\"#\" value=\"\" id=\"first-name\" placeholder=\"Current: ";
String name2_html = 
"\">\r\n"
"      </li>\r\n"
"      <li>\r\n"
"        <button type=\"submit\">Submit</button>\r\n"
"      </li>\r\n"
"    </ul>\r\n"
"  </form>\r\n"
"  </div>\r\n"
"</body>\r\n"
"\r\n"
"</html>\r\n";




String wifi1_html=
"<!DOCTYPE html>\r\n"
"<html>\r\n"
"<head>\r\n"
"<style>\r\n"
"h1{\r\n"
"text-shadow: 2px 1.5px red;\r\n"
"font-family: \"Georgia\", Times, serif;\r\n"
"margin: 5%;\r\n"
"}\r\n"
"body {\r\n"
"  font: normal 18px/1.5 \"Fira Sans\", \"Helvetica Neue\", sans-serif;\r\n"
"  background-color: #2b3e4c;\r\n"
"  color: #fff;\r\n"
"  padding: 50px 0;\r\n"
"}\r\n"
"\r\n"
".container {\r\n"
"  width: 80%;\r\n"
"  max-width: 1200px;\r\n"
"  margin: 0 auto;\r\n"
"}\r\n"
"\r\n"
".container * {\r\n"
"  box-sizing: border-box;\r\n"
"  border-radius: 20px;\r\n"
"}\r\n"
"\r\n"
".flex-outer,\r\n"
".flex-inner {\r\n"
"  list-style-type: none;\r\n"
"  padding: 0;\r\n"
"}\r\n"
"\r\n"
".flex-outer {\r\n"
"  max-width: 800px;\r\n"
"  margin: 0 auto;\r\n"
"}\r\n"
"\r\n"
".flex-outer li,\r\n"
".flex-inner {\r\n"
"  display: flex;\r\n"
"  flex-wrap: wrap;\r\n"
"  align-items: center;\r\n"
"}\r\n"
"\r\n"
".flex-inner {\r\n"
"  padding: 0 8px;\r\n"
"  justify-content: space-between;  \r\n"
"}\r\n"
"\r\n"
".flex-outer > li:not(:last-child) {\r\n"
"  margin-bottom: 20px;\r\n"
"}\r\n"
"\r\n"
".flex-outer li label,\r\n"
".flex-outer li p {\r\n"
"  padding: 8px;\r\n"
"  font-weight: 300;\r\n"
"  letter-spacing: .09em;\r\n"
"  text-transform: uppercase;\r\n"
"}\r\n"
"\r\n"
".flex-outer > li > label,\r\n"
".flex-outer li p {\r\n"
"  flex: 1 0 120px;\r\n"
"  max-width: 220px;\r\n"
"}\r\n"
"\r\n"
".flex-outer > li > label + *,\r\n"
".flex-inner {\r\n"
"  flex: 1 0 220px;\r\n"
"}\r\n"
"\r\n"
".flex-outer li p {\r\n"
"  margin: 0;\r\n"
"}\r\n"
"\r\n"
".flex-outer li input:not([type='checkbox']),\r\n"
".flex-outer li textarea {\r\n"
"  padding: 15px;\r\n"
"  border: none;\r\n"
"}\r\n"
"\r\n"
".flex-outer li button {\r\n"
"  margin-left: auto;\r\n"
"  padding: 8px 16px;\r\n"
"  border: none;\r\n"
"  background: red;\r\n"
"  color: #f2f2f2;\r\n"
"  text-transform: uppercase;\r\n"
"  letter-spacing: .09em;\r\n"
"  border-radius: 2px;\r\n"
"}\r\n"
"\r\n"
".flex-inner li {\r\n"
"  width: 100px;\r\n"
"}\r\n"
"@media screen and (max-width: 600px) {\r\n"
"    .col-25, .col-75, input[type=submit] {\r\n"
"        width: 100%;\r\n"
"        margin-top: 0;\r\n"
"    }\r\n"
"}\r\n"
"</style>\r\n"
"</head>\r\n"
"<body>\r\n"
"<center>\r\n"
"<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n"
"<h1>WiFi settings</h1>\r\n"
"</center>\r\n"
"<div class=\"container\">\r\n"
"  <form action=\"/wifi_commit\">\r\n"
"    <ul class=\"flex-outer\">\r\n"
"      <li>\r\n"
"        <label for=\"first-name\">SSID:</label>\r\n"
"        <input type=\"text\" name=\"#\" value=\"\" id=\"first-name\" placeholder=\"Current: ";
String wifi2_html =
"\">\r\n"
"      </li>\r\n"
"      <li>\r\n"
"        <label for=\"last-name\">Password:</label>\r\n"
"        <input type=\"text\" name=\"#\" value=\"\" id=\"last-name\" placeholder=\"\">\r\n"
"      </li>\r\n"
"      <li>\r\n"
"        <button type=\"submit\">Submit</button>\r\n"
"      </li>\r\n"
"    </ul>\r\n"
"  </form>\r\n"
"  </div>\r\n"
"</body>\r\n"
"\r\n"
"</html>\r\n";




String reboot1_html = 
"<!DOCTYPE html>\r\n"
"<html>\r\n"
"<head>\r\n"
"<style>\r\n"
"body {\r\n"
"    height: 100vh;\r\n"
"    padding: 0;\r\n"
"    margin: 0;\r\n"
"    overflow: hidden;\r\n"
"  background-color: #2b3e4c;\r\n"
"}\r\n"
".wrapper {\r\n"
"    position: relative;\r\n"
"    top: 50%;\r\n"
"    width: 100%;\r\n"
"    text-align: center;\r\n"
"    -webkit-transform: translateY(-50%);\r\n"
"    transform: translateY(-50%);\r\n"
"    z-index: 1;\r\n"
"}\r\n"
".bubbles {\r\n"
"    position: absolute;\r\n"
"    top: 0;\r\n"
"    width: 44px;\r\n"
"    height: 44px;\r\n"
"    margin: auto;\r\n"
"    border-radius: 100%;\r\n"
"    -webkit-animation-name: up-down;\r\n"
"            animation-name: up-down;\r\n"
"    -webkit-animation-duration: 1.3s;\r\n"
"            animation-duration: 1.3s;\r\n"
"    -webkit-animation-timing-function: cubic-bezier(.42, 0, .58, 1);\r\n"
"            animation-timing-function: cubic-bezier(.42, 0, .58, 1);\r\n"
"    -webkit-animation-iteration-count: infinite;\r\n"
"            animation-iteration-count: infinite;\r\n"
"    -webkit-animation-fill-mode: both;\r\n"
"            animation-fill-mode: both;\r\n"
"    -webkit-animation-direction: alternate;\r\n"
"            animation-direction: alternate;\r\n"
"}\r\n"
".tube {\r\n"
"    position: relative;\r\n"
"    display: inline-block;\r\n"
"    width: 45px;\r\n"
"    height: 200px;\r\n"
"    background-color: grey;\r\n"
"    border-radius: 22px;\r\n"
"    overflow: hidden;\r\n"
"}\r\n"
".colored-tube {\r\n"
"    position: absolute;\r\n"
"    top: -80%;\r\n"
"    width: 100%;\r\n"
"    height: 100%;\r\n"
"    border-radius: 22px;\r\n"
"    -webkit-animation-name: up-down;\r\n"
"            animation-name: up-down;\r\n"
"    -webkit-animation-duration: 1.3s;\r\n"
"            animation-duration: 1.3s;\r\n"
"    -webkit-animation-timing-function: cubic-bezier(.42, 0, .58, 1);\r\n"
"            animation-timing-function: cubic-bezier(.42, 0, .58, 1);\r\n"
"    -webkit-animation-iteration-count: infinite;\r\n"
"            animation-iteration-count: infinite;\r\n"
"    -webkit-animation-fill-mode: both;\r\n"
"            animation-fill-mode: both;\r\n"
"    -webkit-animation-direction: alternate;\r\n"
"            animation-direction: alternate;\r\n"
"}\r\n"
".ck1 {\r\n"
"    background-color: #BC86E2;\r\n"
"}\r\n"
"\r\n"
".ck2 {\r\n"
"    background-color: #2BB3E8;\r\n"
"    -webkit-animation-delay: 200ms;\r\n"
"            animation-delay: 200ms;\r\n"
"}\r\n"
"\r\n"
".ck3 {\r\n"
"    background-color: #4eda7b;\r\n"
"    -webkit-animation-delay: 300ms;\r\n"
"            animation-delay: 300ms;\r\n"
"}\r\n"
"\r\n"
".ck4 {\r\n"
"    background-color: #ffd30e;\r\n"
"    -webkit-animation-delay: 400ms;\r\n"
"            animation-delay: 400ms;\r\n"
"}\r\n"
"\r\n"
".ck5 {\r\n"
"    background-color: #ff5a58;\r\n"
"    -webkit-animation-delay: 500ms;\r\n"
"            animation-delay: 500ms;\r\n"
"}\r\n"
"\r\n"
"#b1 {\r\n"
"    background-color: #8861A4;\r\n"
"}\r\n"
"#b2 {\r\n"
"    background-color: #2495C1;\r\n"
"    -webkit-animation-delay: 200ms;\r\n"
"            animation-delay: 200ms;\r\n"
"}\r\n"
"#b3 {\r\n"
"    background-color: #48BB6D;\r\n"
"    -webkit-animation-delay: 300ms;\r\n"
"            animation-delay: 300ms;\r\n"
"}\r\n"
"#b4 {\r\n"
"    background-color: #F1C500;\r\n"
"    -webkit-animation-delay: 400ms;\r\n"
"            animation-delay: 400ms;\r\n"
"}\r\n"
"#b5 {\r\n"
"    background-color: #F35957;\r\n"
"    -webkit-animation-delay: 500ms;\r\n"
"            animation-delay: 500ms;\r\n"
"}\r\n"
"@-webkit-keyframes up-down {\r\n"
"    0% {\r\n"
"        top: 0;\r\n"
"    }\r\n"
"    100% {\r\n"
"        top: 156px;\r\n"
"    }\r\n"
"}\r\n"
"@keyframes up-down {\r\n"
"    0% {\r\n"
"        top: 0;\r\n"
"    }\r\n"
"    100% {\r\n"
"        top: 156px;\r\n"
"    }\r\n"
"}\r\n"
"h1 {\r\n"
"  font-size: xx-large;\r\n"
"  color: #fff;\r\n"
"  width: 100%;\r\n"
"  text-align: center;\r\n"
"  margin: 0;\r\n"
"    position: absolute;\r\n"
"    top: 50%;\r\n"
"    left: 50%;\r\n"
"    transform: translate(-50%, -50%);\r\n"
"  letter-spacing: 4px;\r\n"
"  top: 30%;\r\n"
"  font-weight: bold;\r\n"
"}\r\n"
"h2 {\r\n"
"  font-size: large;\r\n"
"  color: #fff;\r\n"
"  width: 100%;\r\n"
"  text-align: center;\r\n"
"  margin: 0;\r\n"
"    position: absolute;\r\n"
"    top: 50%;\r\n"
"    left: 50%;\r\n"
"    transform: translate(-50%, -50%);\r\n"
"  letter-spacing: 4px;\r\n"
"  top: 80%;\r\n"
"  font-weight: bold;\r\n"
"}\r\n"
"h3 {\r\n"
"  font-size: large;\r\n"
"  color: #fff;\r\n"
"  width: 100%;\r\n"
"  text-align: center;\r\n"
"  margin: 0;\r\n"
"    position: absolute;\r\n"
"    top: 50%;\r\n"
"    left: 50%;\r\n"
"    transform: translate(-50%, -50%);\r\n"
"  letter-spacing: 4px;\r\n"
"  top: 85%;\r\n"
"  font-weight: bold;\r\n"
"}\r\n"
"\r\n"
"</style>\r\n"
"<meta charset=\"UTF-8\">\r\n"
"</head>\r\n"
"<body>\r\n"
"<h1>Rebooting...</h1>\r\n"
"<div class=\"danBkg display-none\"></div>\r\n"
"<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n"
"\r\n"
"<div class=\"wrapper\">\r\n"
"        <div class=\"tube\">\r\n"
"            <div class=\"colored-tube ck1\"> </div>\r\n"
"            <div class=\"bubbles\" id=\"b1\"> </div>\r\n"
"        </div>\r\n"
"        <div class=\"tube\">\r\n"
"            <div class=\"colored-tube ck2\"> </div>\r\n"
"            <div class=\"bubbles\" id=\"b2\"> </div>\r\n"
"        </div>\r\n"
"        <div class=\"tube\">\r\n"
"            <div class=\"colored-tube ck3\"> </div>\r\n"
"            <div class=\"bubbles\" id=\"b3\"> </div>\r\n"
"        </div>\r\n"
"        <div class=\"tube\">\r\n"
"            <div class=\"colored-tube ck4\">&nbsp</div>\r\n"
"            <div class=\"bubbles\" id=\"b4\">&nbsp</div>\r\n"
"        </div>\r\n"
"        <div class=\"tube\">\r\n"
"            <div class=\"colored-tube ck5\">&nbsp</div>\r\n"
"            <div class=\"bubbles\" id=\"b5\">&nbsp</div>\r\n"
"        </div>\r\n"
"    </div>\r\n"
"\r\n"
"    <div class=\"danBkg display-none\">&nbsp</div>\r\n"
" <h2>Setting changed to:</h2>\r\n"
" <h3>";
String reboot2_html = 
"</h3>\r\n"
"</body>\r\n"
"</html>\r\n";
